### ISSUE TITLE
DateScalar throws exception when attempting to serialize Instant

### ISSUE THREAD

**Issue by xenoterracide** [Urigo/graphql-scalars#1744]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Make sure to fork this template and run `yarn generate` in the terminal.
>
> Please make sure the GraphQL Scalars package version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

```
graphql.schema.CoercingSerializeException: Unable to turn TemporalAccessor into full date because of : 'Unsupported field: YearOfEra'.
	at graphql.scalars.datetime.DateScalar$1.serialize(DateScalar.java:51) ~[graphql-java-extended-scalars-18.1.jar:?]
	at graphql.scalars.datetime.DateScalar$1.serialize(DateScalar.java:34) ~[graphql-java-extended-scalars-18.1.jar:?]
```

**To Reproduce**

Seems to be simply serializing an `Instant`

**Expected behavior**

serializes fine...

**Environment:**

- OS: Darwin 5c52309d33e3 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64 i386 Darwin
- GraphQL Scalars Version: 18.1
- NodeJS:

**Additional context**

**Comment by xenoterracide** [comment]
wrong library, sorry
